# Generated by Django 2.2.4 on 2019-08-30 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
            ],
        ),
    ]
